// <auto-generated />
using DressShop.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DressShop.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231224214743_addDescriptionToProduct")]
    partial class addDescriptionToProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DressShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Elegant"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Simple"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Leather"
                        });
                });

            modelBuilder.Entity("DressShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Elegant Satin dress perfect for wedding",
                            ImageUrl = "",
                            ListPrice = 105.0,
                            Price = 75.0,
                            Price100 = 25.0,
                            Price50 = 50.0,
                            Title = "Satin Red Dress"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Classy and Unique dress, made with love to celebreate feelings",
                            ImageUrl = "",
                            ListPrice = 125.0,
                            Price = 85.0,
                            Price100 = 35.0,
                            Price50 = 40.0,
                            Title = "Foil Print Slip Dress"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Casual dress, perfect for holidays fashion week",
                            ImageUrl = "",
                            ListPrice = 125.0,
                            Price = 85.0,
                            Price100 = 35.0,
                            Price50 = 40.0,
                            Title = "Shirt Dress With Belt"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Casual every day dress, look stylish",
                            ImageUrl = "",
                            ListPrice = 55.0,
                            Price = 30.0,
                            Price100 = 10.0,
                            Price50 = 20.0,
                            Title = "Shiny Midi Dress"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 6,
                            Description = "Black Leather dress for unforgettable look",
                            ImageUrl = "",
                            ListPrice = 92.0,
                            Price = 80.0,
                            Price100 = 25.0,
                            Price50 = 55.0,
                            Title = "Draped Faux Long Leather Dress"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            Description = "Short leather dress, best choise for date night",
                            ImageUrl = "",
                            ListPrice = 35.0,
                            Price = 25.0,
                            Price100 = 5.0,
                            Price50 = 10.0,
                            Title = "Short Draped Faux Leather Dress "
                        });
                });

            modelBuilder.Entity("DressShop.Models.Product", b =>
                {
                    b.HasOne("DressShop.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
